#!/usr/bin/env bash

# shellcheck shell=bash
# shellcheck disable=SC1090,SC1091,SC2034,SC2048,SC2086,SC2154

function _strip_all() {

  # Usage: _strip_all "string" "pattern"
  printf '%s\n' "${1//$2}"

}
