#!/usr/bin/env bash

# shellcheck shell=bash
# shellcheck disable=SC1090,SC1091,SC2034,SC2154

function _trim_string() {

  # Usage: _trim_string "   example   string    "

  : "${1#"${1%%[![:space:]]*}"}"
  : "${_%"${_##*[![:space:]]}"}"

  printf '%s\n' "$_"

}
