#!/usr/bin/env bash

# shellcheck shell=bash
# shellcheck disable=SC1090,SC1091,SC2034,SC2154

_get_term_size() {

  # Usage: _get_term_size

  # (:;:) is a micro sleep to ensure the variables are
  # exported immediately.
  shopt -s checkwinsize; (:;:)
  printf '%s\n' "$LINES $COLUMNS"

}
