.\" Manpage for __NAME__.
.\" Contact __EMAIL__.
.TH man 8 "__DATE__" "__VERSION__" "__NAME__ man page"
.SH NAME
__NAME__ \- __SHORT_DESCRIPTION__
.SH SYNOPSIS
__NAME__ <option|long-option>
.SH DESCRIPTION
__NAME__ __LONG_DESCRIPTION__
.SH OPTIONS
-h|--help
        show this message

.SH SEE ALSO
__REPO__/__NAME__
.SH BUGS
No known bugs.
.SH AUTHOR
__AUTHOR__ (__EMAIL__)
