#!/usr/bin/env bash

# shellcheck shell=bash
# shellcheck disable=SC1090,SC1091,SC2034,SC2154

################################################################################
#################### External variables/functions and libs #####################
################################################################################

# Set of external files with variables, functions and other. The configuration
# of each of them is in lib directory. The fd_stack array stores the names of
# attached files. If you create a new file with some interesting function,
# name it appropriately and insert to the array.
if [[ "${#_fd_stack[@]}" -ne 0 ]] ; then

  for _fd in "${_fd_stack[@]}" ; do

    # shellcheck disable=SC2154
    _fd_full_path="${_lib}/${_fd}"

    if [[ ! -z "$_fd_full_path" ]] && [[ -e "$_fd_full_path" ]] ; then

      # If the file exists is loaded.
      # shellcheck disable=SC1090
      source "$_fd_full_path"

    elif [[ -z "$_fd_full_path" ]] ; then

      printf "incorrectly loaded '%s' file (incorrect filename)" "$_fd_full_path"
      _exit_ "1"

    else

      printf "incorrectly loaded '%s' file (does not exist?)" "$_fd_full_path"
      _exit_ "1"

    fi

  done

fi
