#!/usr/bin/env bash

# shellcheck shell=bash
# shellcheck disable=SC1090,SC1091,SC2034,SC2154,SC2173

################################################################################
################## The configuration parameters of the script ##################
################################################################################

# Bash 'Strict Mode':
#   errexit  - exit the script if any statement returns a non-true return value
#   pipefail - exit the script if any command in a pipeline errors
#   nounset  - exit the script if you try to use an uninitialised variable
#   xtrace   - display debugging information
set -o pipefail

# Internal field separator (more flexible):
#   IFS_ORIG="$IFS"
#   IFS_HACK=$'\n\t'
#   IFS="$IFS_HACK"

# PATH env variable setup:
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# Setting permissions in the script environment:
#   0022 - less restrictive settings (default value)
#   0027 - for better security than above
#   0077 - only for user access (more restrictive)
umask 0027

# Set script version.
readonly _version="__VERSION__"

# Run script only with you're root.
if_root="true"

# Enable/disable output colors.
s_color="true"

# Set default colors for printf.
b_trgb="1;2;30"
e_trgb="1;1;31"
g_trgb="1;1;32"
d_trgb="4;1;33"
s_trgb="2;2;34"
h_trgb="1;2;36"
p_trgb="2;2;37"
c_trgb="1;1;38"
x_trgb="1;2;38"

# We place here used commands at script runtime, as strings to anything
# unnecessarily run.
readonly commands=("basename" "dirname" "stat" "date" "grep" "cut" \
                   "sed" "gzip" "tar" "mktemp")

# Set of external files with variables, functions and other.
# Example:
#   - create lib/kill_process - file with your function
#   - _fd_stack=("kill_process") - says to include this file in the script
readonly _fd_stack=()

# Catch the listed SIGNALS, which may be signal names with or without the SIG
# prefix, or signal numbers. By default, only the signal 0 or EXIT is supported.
trap "_get_trap_SIG EXIT" EXIT

# trap "_get_trap_SIG SIGS" SIGHUP SIGTERM SIGKILL SIGINT
