#!/usr/bin/env bash

# shellcheck shell=bash
# shellcheck disable=SC1090,SC1091,SC2034,SC2048,SC2086,SC2154

function _count() {

  # Usage: _count /path/to/dir/*
  #        _count /path/to/dir/*/

  printf '%s\n' "$#"

}
