#!/usr/bin/env bash

# shellcheck shell=bash
# shellcheck disable=SC1090,SC1091,SC2034,SC2048,SC2086,SC2154

_extract_lines() {

  # Usage: extract file "opening marker" "closing marker"

  while IFS=$'\n' read -r line ; do

    [[ "$extract" && "$line" != "$3" ]] && \
    printf '%s\n' "$line"

    [[ "$line" == "$2" ]] && extract=1
    [[ "$line" == "$3" ]] && extract=

  done < "$1"

}
