#!/usr/bin/env bash

# shellcheck shell=bash
# shellcheck disable=SC1090,SC1091,SC2034,SC2048,SC2086,SC2154

_head_num() {

  # Usage: _head_num "n" "file"

  mapfile -tn "$1" line < "$2"
  printf '%s\n' "${line[@]}"

}
