#!/usr/bin/env bash

# shellcheck shell=bash
# shellcheck disable=SC1090,SC1091,SC2034,SC2048,SC2086,SC2154

_lines() {

  # Usage: _lines "file"

  mapfile -tn 0 lines < "$1"
  printf '%s\n' "${#lines[@]}"

}
