#!/usr/bin/env bash

# shellcheck shell=bash
# shellcheck disable=SC1090,SC1091,SC2034,SC2048,SC2086,SC2154

_tail_num() {

  # Usage: _tail_num "n" "file"

  mapfile -tn 0 line < "$2"
  printf '%s\n' "${line[@]: -$1}"

}
