#!/usr/bin/env bash

# shellcheck shell=bash
# shellcheck disable=SC1090,SC1091,SC2034,SC2048,SC2086,SC2154

function _check_conn() {

  # Usage: _check_conn "protocol" ip address" "port number"

  local prot="$1"
  local addr="$2"
  local port="$3"

  timeout 10 bash -c "</dev/${prot}/${addr}/${port}" >>/dev/null 2>&1

  _state="$?"

  if [[ "$_state" -eq 0 ]] ; then

    _conn="connected"

  else

    _conn="timed out"

  fi

  printf '%s\n' "$_conn"

}
