#!/usr/bin/env bash

# shellcheck shell=bash
# shellcheck disable=SC1090,SC1091,SC2034,SC2048,SC2086,SC2154

_random_array_element() {

  # Usage: _random_array_element "array"

  local arr=("$@")
  printf '%s\n' "${arr[RANDOM % $#]}"

}
